### PR TITLE
Plug small security hole in travis.yml

### PR DESCRIPTION
**Pull request by chbatey**
Verify the tarball before executing the `oc` binary, in case of compromise.

### CODE REVIEW

**Review by raboof — APPROVED** [review]
Still seems good to me :laughing:

**Comment by dwijnand** [comment]
Build is broken.

**Comment by raboof** [comment]
(build failure seems unrelated to this PR though - we should install AdoptOpenJDK with jabba instead of relying on travis, as that doesn't provide openjdk8 anymore with this Ubuntu version)

**Comment by chbatey** [comment]
Merged master into it with the java thing fixed

**Comment by chbatey** [comment]
Thanks @jsravn

**Pull request merged**
